spring.application.name=hub

spring.datasource.url=jdbc:postgresql://localhost:5432/hub_db
spring.datasource.username=postgres
spring.datasource.password=thay

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.jwt.secret=9f8a7b6c5d4e3f2g1h0i9j8k7l6m5n4o3p2q1r0s9t8u7v6w5x4y3z2a1b0c9d8e
